// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvjYLbBsWuYNHGn4HB3TmSKSYBoWmmVOQ',
    appId: '1:428240672889:web:27cab272b209304daedca8',
    messagingSenderId: '428240672889',
    projectId: 'expense-tra-1a7e2',
    authDomain: 'expense-tra-1a7e2.firebaseapp.com',
    storageBucket: 'expense-tra-1a7e2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7owPypvWMw6q33va5MIQGVdJ_MDeUfjQ',
    appId: '1:428240672889:android:a09bb578b039b994aedca8',
    messagingSenderId: '428240672889',
    projectId: 'expense-tra-1a7e2',
    storageBucket: 'expense-tra-1a7e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxpoogO3hZUHEe-ywG3NoKjr6xhu_e6MY',
    appId: '1:428240672889:ios:3dff4bfd2b602cb5aedca8',
    messagingSenderId: '428240672889',
    projectId: 'expense-tra-1a7e2',
    storageBucket: 'expense-tra-1a7e2.firebasestorage.app',
    iosBundleId: 'com.example.expTracker',
  );
}
